version: 2

jobs:
  build-python27:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            pipenv run ./manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
  build-python36:
    docker:
      - image: circleci/python:3.6.4
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - run:
          name: run tests
          command: |
            pipenv run ./manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python36